repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.8.0
    hooks:
      - id: ruff
        args: [--select, "E,W,F", --ignore, "E501", --fix]
        files: 'engine-app/backend/.*\.py$'
